accounts/urls.py
from django.conf.urls import url, include
from userena import views as userena_views
from userena.forms import AuthenticationForm
from accounts import views as account_views
from .forms import CustomSignupForm, ModifiedAuthenticationForm

urlpatterns = [
    url(r'^signup/$', userena_views.signup, {'signup_form': CustomSignupForm, 'template_name': 'accounts/signup.html'}, name="signup"),
    url(r'^signin/$', userena_views.signin, {'auth_form': ModifiedAuthenticationForm}),
    url(r'^', include('userena.urls')),


]

trabd/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import urls as accounts_urls
from general import urls as general_urls
from voting import urls as voting_urls
from voting import views as voting_views


urlpatterns = [
    url(r'^admin/', include('loginas.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', voting_views.show_index, name='home'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^positions/', include(voting_urls, namespace="voting")),
    url(r'^general/', include(general_urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from voting import views as voting_views
from forms import NominationForm

urlpatterns = [
    url(r'^(?P<entity>(club|council))/$', voting_views.list_positions, name='list_positions'),
    url(r'^(?P<position_id>\d+)/add_nominee/$', voting_views.add_nominee, name='add_nominee'),
    url(r'^(?P<position_id>\d+)/(?P<nomination_id>\d+)/$', voting_views.show_nomination, name='show_nomination'),
    url(r'^(?P<position_id>\d+)/add_nominee/thanks/$', TemplateView.as_view(template_name='voting/nomination_thanks.html'), name='nomination_thanks'),
    url(r'^voting/ajax$', voting_views.handle_vote, name='handle_vote'),
    url(r'^voting/$', voting_views.show_voting_index, name='show_voting_index'),
    url(r'^voting/stats/$', voting_views.indicators, name='indicators'),    
    url(r'^voting/stats/(?P<position_id>\d+)/$', voting_views.list_votes_per_position, name='list_votes_per_position'),

    url(r'^nominees/(?P<entity>(?:club|council))/$', voting_views.announce_nominees, name='announce_nominees'),
    url(r'^winners/(?P<entity>(?:club|council))/$', voting_views.announce_winners, name='announce_winners'),
    url(r'^user-autocomplete/$', voting_views.UserAutocomplete.as_view(), name='user-autocomplete'),
    # Obsolete
    url(r'^voting_closed/$', RedirectView.as_view(pattern_name="show_voting_index"), name='voting_closed'),
    url(r'^announce_(?P<entity>(club|council))_nominees/$', RedirectView.as_view(pattern_name="announce_nominees")),
]

accounts/models.py
# -*- coding: utf-8  -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from userena.models import UserenaBaseProfile


gender_choices = (
    ('', '--'),
    ('F', 'طالبات'),
    ('M', 'طلاب'),
)

college_choices = (
    ('', '--'),
    ('M', 'كلية الطب'),
    ('A', 'كلية العلوم الطبية التطبيقية'),
    ('P', 'كلية الصيدلة'),
    ('D', 'كلية طب الأسنان'),
    ('B', 'كلية العلوم و المهن الصحية'),
    ('N', 'كلية التمريض'),
    ('I', ' كلية الصحة العامة والمعلوماتية الصحية'),
)

city_choices = (
    ('', '--'),
    ('R', 'الرياض'),
    ('J', 'جدة'),
    ('A', 'الأحساء'),
)

year_choices = (
    ('', "--"),
    ('1', 'السنة الأولى'),
    ('2', "السنة الثانية"),
    ('3', "السنة الثالثة"),
    ('4', "السنة الرابعة"),
    ('5', "السنة الخامسة"),
    ('6', "السنة السادسة"),
    ('7', "سنة الامتياز"),
)

class College(models.Model):
    name = models.CharField("الاسم", max_length=1,
                            choices=college_choices)
    city = models.CharField("المدينة", max_length=1,
                            choices=city_choices)
    gender = models.CharField("الجنس", max_length=1,
                              choices=gender_choices)

    def __unicode__(self):
        return "%s (%s - %s)" % (self.get_name_display(),
                                 self.get_city_display(),
                                 self.get_gender_display())

    class Meta:
        # For the admin interface.
        verbose_name = "كلية"
        verbose_name_plural = "الكليات"

class Profile(UserenaBaseProfile):
    user = models.OneToOneField(User, verbose_name="مستخدمـ/ـة")
    ar_first_name = models.CharField(u'الاسم الأول', max_length=30)
    ar_middle_name = models.CharField(u'الاسم الأوسط', max_length=30)
    ar_last_name = models.CharField('الاسم الأخير', max_length=30)
    en_first_name = models.CharField(u'الاسم الأول', max_length=30)
    en_middle_name = models.CharField('الاسم الأوسط', max_length=30)
    en_last_name = models.CharField(u'الاسم الأخير', max_length=30)
    college = models.ForeignKey(College, verbose_name="الكلية", null=True)
    college_year = models.CharField("سنة الدراسة", max_length=1, choices=year_choices, default='')
    city = models.CharField("المدينة", max_length=1, choices=city_choices)
    gender = models.CharField("الجنس", max_length=1, choices=gender_choices)
    mobile_number = models.CharField("رقم الجوال", max_length=14)
    student_id = models.IntegerField("الرقم الجامعي", unique=True, null=True)
    submission_date = models.DateTimeField("تاريخ التسجيل", auto_now_add=True)
    modification_date = models.DateTimeField("تاريخ التعديل", auto_now=True, null=True)

    def get_gender(self):
        return self.gender

    def get_ar_full_name(self):
        ar_fullname = None
        try:
            # If the Arabic first name is missing, let's assume the
            # rest is also missing.
            if self.ar_first_name:
                ar_fullname = " ".join([self.ar_first_name,
                                        self.ar_middle_name,
                                        self.ar_last_name])
        except AttributeError: # If the user has their details missing
            pass

        return ar_fullname

    def get_en_full_name(self):
        en_fullname = None
        try:
            # If the English first name is missing, let's assume the
            # rest is also missing.
            if self.en_first_name:
                en_fullname = " ".join([self.en_first_name,
                                        self.en_middle_name,
                                        self.en_last_name])
        except AttributeError: # If the user has their details missing
            pass

        return en_fullname

    class Meta:
        verbose_name = 'الحساب'
        verbose_name_plural = 'الحسابات'

accounts/forms.py
# -*- coding: utf-8  -*-
from __future__ import unicode_literals
from django import forms
from django.contrib.auth import authenticate
from django.utils.translation import ugettext as _
from accounts.models import Profile
from userena.forms import SignupForm, EditProfileForm
from userena.models import UserenaBaseProfile
from .models import College, gender_choices, college_choices, city_choices


class CustomSignupForm(SignupForm):
    ar_first_name = forms.CharField(label=Profile._meta.get_field('ar_first_name').verbose_name,
                                max_length=30)
    ar_middle_name = forms.CharField(label=Profile._meta.get_field('ar_middle_name').verbose_name,
                                max_length=30)
    ar_last_name = forms.CharField(label=Profile._meta.get_field('ar_last_name').verbose_name,
                                max_length=30)
    en_first_name = forms.CharField(label=Profile._meta.get_field('en_first_name').verbose_name,
                                max_length=30)
    en_middle_name = forms.CharField(label=Profile._meta.get_field('en_middle_name').verbose_name,
                                max_length=30)
    en_last_name = forms.CharField(label=Profile._meta.get_field('en_last_name').verbose_name,
                                max_length=30)
    en_last_name = forms.CharField(label=Profile._meta.get_field('en_last_name').verbose_name,
                                max_length=30)
    username = None
    mobile_number = forms.CharField(label=Profile._meta.get_field('mobile_number').verbose_name)
    student_id = forms.IntegerField(label=Profile._meta.get_field('student_id').verbose_name)

    gender = forms.CharField(label=u"الجندر", max_length=1, widget=forms.Select(choices=gender_choices))

    college = forms.CharField(label=u"الكلية", max_length=1, widget=forms.Select(choices=college_choices))

    city = forms.CharField(label=u"المدينة", max_length=1, widget=forms.Select(choices=city_choices))

    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = u'البريد الإلكتروني الجامعي'
        self.fields['password1'].label = 'كلمة السر'
        self.fields['password2'].label = 'تأكيد كلمة السر'

    def clean(self, *args, **kwargs):
        cleaned_data = super(CustomSignupForm, self).clean(*args, **kwargs)
        if 'email' in cleaned_data:
            cleaned_data['email'] = cleaned_data['email'].lower()
            if not cleaned_data['email'].endswith('ksau-hs.edu.sa'):
                email_msg = u"الرجاء إدخال بريد جامعي"
                self._errors['email'] = self.error_class([email_msg])
                del self.cleaned_data['email']

        if 'gender' in cleaned_data and \
           'city' in cleaned_data and \
           'college' in cleaned_data:
            # Make sure that the college choice is valid.
            try:
                self.college = College.objects.get(
                    name=cleaned_data['college'],
                    city=cleaned_data['city'],
                    gender=cleaned_data['gender'])
            except College.DoesNotExist:
                college_msg = u"ليست كلية مسجلة."
                # Add an error message to specific fields.
                self._errors['college'] = self.error_class([college_msg])
                self._errors['city'] = self.error_class([college_msg])
                self._errors['gender'] = self.error_class([college_msg])
                # Remove invalid fields
                del cleaned_data['college']
                del cleaned_data['city']
                del cleaned_data['gender']
        return cleaned_data

    def save(self):
        """
        Override the save method to save the new fields

        """
        # Derive usernames from email address
        self.cleaned_data['username'] = self.cleaned_data['email'].split('@')[0]
        # First save the parent form and get the user.
        new_user = super(CustomSignupForm, self).save()

        # Get the profile, the `save` method above creates a profile for each
        # user because it calls the manager method `create_user`.
        # See: https://github.com/bread-and-pepper/django-userena/blob/master/userena/managers.py#L65
        user_profile = new_user.profile

        user_profile.ar_first_name = self.cleaned_data['ar_first_name']
        user_profile.ar_middle_name = self.cleaned_data['ar_middle_name']
        user_profile.ar_last_name = self.cleaned_data['ar_last_name']
        user_profile.en_first_name = self.cleaned_data['en_first_name']
        user_profile.en_middle_name = self.cleaned_data['en_middle_name']
        user_profile.en_last_name = self.cleaned_data['en_last_name']
        user_profile.student_id = self.cleaned_data['student_id']
        print self.cleaned_data['student_id']
        user_profile.mobile_number = self.cleaned_data['mobile_number']
        user_profile.gender = self.cleaned_data['gender']
        user_profile.city = self.cleaned_data['city']
        user_profile.college = self.college

        user_profile.save()

        # Userena expects to get the new user from this form, so return the new
        # user.
        return new_user

class CustomEditProfileForm(EditProfileForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        fields = ['ar_first_name', 'ar_middle_name', 'ar_last_name',
                  'en_first_name', 'en_middle_name', 'en_last_name',
                  'city', 'gender', 'mobile_number', ]

class ModifiedAuthenticationForm(forms.Form):
    identification = forms.CharField(label=u"البريد",
                                        widget=forms.TextInput(attrs={'class': 'required'}),
                                        max_length=75,
                                        error_messages={'required': u"رجاءً أدخل بريدك الجامعي."})
    password = forms.CharField(label="كلمة السرّ",
                               widget=forms.PasswordInput(attrs={'class': 'required'}, render_value=False))
    remember_me = forms.BooleanField(widget=forms.CheckboxInput(),
                                     required=False,
                                     label=u'تذكرني (مدّة شهر)')


    def clean(self):
        """
        Checks for the identification and password.

        If the combination can't be found will raise an invalid sign in error.

        """
        identification = self.cleaned_data.get('identification')
        password = self.cleaned_data.get('password')

        if identification and password:
            username = identification.split('@')[0]
            username = username.lower().strip()

            # The final username should be returned to userena to
            # process.
            self.cleaned_data['identification'] = username

            user = authenticate(username=username, password=password)

            if user is None:
                if not identification.endswith('ksau-hs.edu.sa'):
                    email_msg = u"الرجاء إدخال بريد جامعي"
                    self._errors['identification'] = self.error_class([email_msg])
                    del self.cleaned_data['identification']
                else:
                    raise forms.ValidationError("ليست البيانات صحيحة!")
            return self.cleaned_data

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from forms import SignupForm

from userena import views as userena_views









# Create your views here.


#def signup_extra(request, signup_form, template_name):
#    if request.method == 'POST':
#        form = SignupForm(request.POST)
#        # extra_context for Userena's view
#        extra_context = {'form': form}
#        return userena_views.signup(request, extra_context=extra_context)###

accounts/templates/accounts/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="ar" dir="rtl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>بوابة ترابط | {% block title %}{% endblock %}</title>

        <!-- Bootstrap -->
        <link href="{% static 'bdtask/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Bootstrap rtl -->
        <link href="{% static 'bdtask/assets/bootstrap-rtl/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Pe-icon-7-stroke -->
        <link href="{% static 'bdtask/assets/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" rel="stylesheet" type="text/css"/>
        <!-- style css -->
        <link href="{% static 'bdtask/assets/dist/css/styleBD.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Theme style rtl -->
        <link href="{% static 'bdtask/assets/dist/css/styleBD-rtl.css' %}" rel="stylesheet" type="text/css"/>
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto);
@font-face {
    font-family: 'GE Dinar One';
    font-weight: lighter;
    font-size: xx-large;
    src: url("{% static 'fonts/ge-dinar-one-light.woff' %}");
}
@font-face {
    font-family: 'GE Dinar One';
    font-weight: normal;
    src: url("{% static 'fonts/ge-dinar-one-med.woff' %}");
}

body, h1, h2, .header-title h3, h4{
    font-family: 'GE Dinar One';
}

.panel .panel-heading h3{
 letter-spacing: 0;
}

.english-field input {
    direction: ltr;
    text-align: left;
    font-family: 'Roboto', "GE Dinar One", sans-serif;
}

h3{
  width: 100%;
}

footer.main-footer{
   position: fixed;
   bottom: 0;
   width: 100%;
   margin-right: 0;
}

footer a{
 color: inherit;
}
</style>

{% if request.get_host == 'trabdportal.com' or request.get_host == 'www.trabdportal.com' %}
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  {% if user.is_authenticated %}
  _paq.push(['setUserId', '{{ user.username }}']);
  {% endif %}
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//trabdportal.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
{% endif %}
    </head>
    <body>
        <!-- Content Wrapper -->
        <div class="login-wrapper">
            <div class="back-link">
                <a href="{% url 'home' %}" class="btn btn-success">العودة للصفحة الرئيسية</a>
            </div>
            <div class="container-center">
               {% block content %}{% endblock %}
            </div>
        </div>
            <footer class="main-footer">
                <strong>بُنيَ بأيدٍ طلابيّة. <a href="https://github.com/SAlkhairy/trabd/" target="_blank">حقّك في النسخ مكفول</a>. <i class="fa fa-heart color-green"></i></strong>
            </footer>
        <!-- /.content-wrapper -->
        <!-- jQuery -->
        <script src="{% static 'bdtask/assets/plugins/jQuery/jquery-1.12.4.min.js' %}" type="text/javascript"></script>
        <!-- bootstrap js -->
        <script src="{% static 'bdtask/assets/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
        {% block customscript %}{% endblock %}
    </body>
</html>

accounts/templates/accounts/home.html
{% extends 'base.html' %}{% load staticfiles %}
{% block title %}الرئيسية{% endblock %}
{% block header %}
<h1>أهلا بكم!</h1>
<small>بوابة ترابط</small>
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
</ol>
{% endblock %}
{% block content %}
<style>
    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }
    .panel{
      height: 100%;
    }
    .panel img{
      margin-right: auto;
      margin-left: auto;
      max-height: 200px;
    }
    .row-eq-height a{
      color: inherit;
    }
    .row-eq-height h2{
      margin-top: 20px;
    }
</style>
<p class="text-center" style="font-size: 25px;">أهلا بكم في بوابة المجلس الاستشاري الطلابي!</p>
{% if sac_year.is_nomination_open or sac_year.is_announcement_due %}
<p style="font-size: 20px;">
{% if sac_year.is_nomination_open %}
البوابة الآن مفتوحة للترشّح لانتخابات {{ sac_year }}!
{% elif sac_year.is_announcement_due %}
تمّ الإعلان عن المُرشَحين والمُرشّحات لانتخابات {{ sac_year }}!
{% endif %}
</p>
<div class="row row-eq-height">
    <div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-2 text-center">
        <div class="panel panel-bd">
            <div class="panel-body">
                <div class="statistic-box">
                    <a href="{% if sac_year.is_nomination_open %}{% url 'voting:list_positions' 'club' %}{% elif sac_year.is_announcement_due %}{% url 'voting:announce_nominees' 'club' %}{% endif %}">
                        <img class="img-responsive" src="{% static 'images/logos/student-club.png' %}">
                        <h2>نادي الطلاب</h2>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 text-center">
        <div class="panel panel-bd">
            <div class="panel-body">
                <div class="statistic-box">
                    <a href="{% if sac_year.is_nomination_open %}{% url 'voting:list_positions' 'council' %}{% elif sac_year.is_announcement_due %}{% url 'voting:announce_nominees' 'council' %}{% endif %}">
                        <img class="img-responsive" src="{% static 'images/logos/logo-no-text.png' %}">
                        <h2>المجلس الاستشاري الطلابي</h2>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% if request.get_host == 'trabdportal.com' or request.get_host == 'www.trabdportal.com' %}
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  {% if user.is_authenticated %}
  _paq.push(['setUserId', '{{ user.username }}']);
  {% endif %}
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//trabdportal.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
{% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}{% load bootstrap3 %}
{% block title %}التسجيل{% endblock %}
{% block content %}

 

{% bootstrap_form_errors form %}


                <div class="panel panel-bd">
                    <div class="panel-heading">
                        <div class="view-header">
                            <div class="header-icon">
                                <i class="pe-7s-unlock"></i>
                            </div>
                            <div class="header-title">
                                <h3>التسجيل</h3>
                                <small><strong>الرجاء إدخال البيانات أدناه للتسجيل.</strong></small>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <form method="post" id="loginForm" novalidate>
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                <h4 class="text-center">الاسم بالعربيّة</h4>
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                    {% bootstrap_field form.ar_first_name %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                    {% bootstrap_field form.ar_middle_name %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                    {% bootstrap_field form.ar_last_name %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                <hr>
                                <h4 class="text-center">الاسم بالإنجليزية</h4>
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.en_first_name %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.en_middle_name %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.en_last_name %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    <hr>
                                    {% bootstrap_field form.email %}
                                    <span class="help-block small">التسجيل في بوابة ترابط مقتصر على طلاب وطالبات جامعة الملك سعود بن عبد العزيز للعلوم الصحيّة.</span>
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.mobile_number %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.student_id %}
                                    <span class="help-block small">هذا هو الرقم الذي يبدأ بسنة دخولك للجامعة، مثلا: 34-080-0101</span>
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.gender %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.city %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2 english-field">
                                    {% bootstrap_field form.college %}
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                    {% bootstrap_field form.password1 %}
                                    <span class="help-block small">كلمة سرّك التي لا يحزرها أحد!</span>
                                </div>
                                <div class="form-group col-lg-8 col-lg-offset-2">
                                    {% bootstrap_field form.password2 %}
                                    <span class="help-block small">أعد كتابة كلمة السرّ رجاءً</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-12 checkbox checkbox-success">
                                    <input id="checkbox" type="checkbox">
                                    <label for="checkbox">أقر بأن جميع المعلومات التي تم تعبئتها في نموذج التسجيل  صحيحة وأنه في حال اكتشاف أي معلومات مغلوطة يحق للجنة الانتخابات استبعادي من العملية الانتخابية وذلك يشمل التصويت والترشّح.</label>
                                </div>
                            </div>

                            <div>
                                <button id="submit" disabled class="btn btn-warning">سجّلني</button>
                            </div>
                        </form>
                    </div>
                </div>
{% endblock %}
{% block customscript %}
<script>
$(function(){
   $("input[type=checkbox]").change(function(){
      if ($("input[type=checkbox]:checked").length == 1){
       $("#submit").removeAttr('disabled');
      } else {
       $("#submit").attr('disabled', 'disabled');
      }
   })
});
</script>
{% endblock %}