trabd/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import urls as accounts_urls
from general import urls as general_urls
from voting import urls as voting_urls
from voting import views as voting_views


urlpatterns = [
    url(r'^admin/', include('loginas.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', voting_views.show_index, name='home'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^positions/', include(voting_urls, namespace="voting")),
    url(r'^general/', include(general_urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from voting import views as voting_views
from forms import NominationForm

urlpatterns = [
    url(r'^(?P<entity>(club|council))/$', voting_views.list_positions, name='list_positions'),
    url(r'^(?P<position_id>\d+)/add_nominee/$', voting_views.add_nominee, name='add_nominee'),
    url(r'^(?P<position_id>\d+)/(?P<nomination_id>\d+)/$', voting_views.show_nomination, name='show_nomination'),
    url(r'^(?P<position_id>\d+)/add_nominee/thanks/$', TemplateView.as_view(template_name='voting/nomination_thanks.html'), name='nomination_thanks'),
    url(r'^voting/ajax$', voting_views.handle_vote, name='handle_vote'),
    url(r'^voting/$', voting_views.show_voting_index, name='show_voting_index'),
    url(r'^voting/stats/$', voting_views.indicators, name='indicators'),    
    url(r'^voting/stats/(?P<position_id>\d+)/$', voting_views.list_votes_per_position, name='list_votes_per_position'),

    url(r'^nominees/(?P<entity>(?:club|council))/$', voting_views.announce_nominees, name='announce_nominees'),
    url(r'^winners/(?P<entity>(?:club|council))/$', voting_views.announce_winners, name='announce_winners'),
    url(r'^user-autocomplete/$', voting_views.UserAutocomplete.as_view(), name='user-autocomplete'),
    # Obsolete
    url(r'^voting_closed/$', RedirectView.as_view(pattern_name="show_voting_index"), name='voting_closed'),
    url(r'^announce_(?P<entity>(club|council))_nominees/$', RedirectView.as_view(pattern_name="announce_nominees")),
]

voting/models.py
# -*- coding: utf-8  -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Count, Max
from django.utils import timezone
from accounts.models import Profile, College
from .managers import YearQuerySet

city_choices = (
    ('', 'عامة'),
    ('R', 'الرياض'),
    ('J', 'جدة'),
    ('A', 'الأحساء'),
    )


class SACYear(models.Model):
    start_date = models.DateTimeField("تاريخ البداية")
    end_date = models.DateTimeField("تاريخ النهاية")
    election_nomination_start_datetime = models.DateTimeField("تاريخ بداية الترشيحات")
    election_nomination_end_datetime = models.DateTimeField("تاريخ نهاية الترشيحات")
    election_nomination_announcement_datetime = models.DateTimeField("تاريخ إعلان الترشيحات", null=True)
    election_vote_start_datetime = models.DateTimeField("تاريخ بداية التصويت", null=True, blank=True)
    election_vote_end_datetime = models.DateTimeField("تاريخ نهاية التصويت", null=True, blank=True)
    riyadh_results_datetime = models.DateTimeField("تاريخ إعلان النتائج في الرياض", null=True, blank=True)
    jeddah_results_datetime = models.DateTimeField("تاريخ إعلان النتائج في جدة", null=True, blank=True)
    alahsa_results_datetime = models.DateTimeField("تاريخ إعلان النتائج في الأحساء", null=True, blank=True)
    objects = YearQuerySet.as_manager()

    class Meta:
        verbose_name = 'السنة الأكاديمية'
        verbose_name_plural = "السنوات الأكاديمية"

    def get_next_year_name(self):
        return "%s-%s" % (self.start_date.year + 1, self.end_date.year + 1)

    def is_nomination_near(self):
        delta_time = self.election_nomination_start_datetime - timezone.now()
        delta_days = delta_time.days
        return delta_days <= 10

    def is_nomination_open(self):
        # If no election nomination start was specified, let's
        # consider the elections closed.  Otherwise, respect the
        # specified time.
        return self.election_nomination_start_datetime and \
               self.election_nomination_end_datetime and \
               self.election_nomination_start_datetime < timezone.now() and \
               self.election_nomination_end_datetime > timezone.now()

    def is_announcement_due(self):
        # If no announcement date is specified,
        # we'll consider the announcement not due;
        # so that, during nominations, non-rejected nominees (all of them)
        # will not appear until the proper date.
        return self.election_nomination_announcement_datetime and \
            self.election_nomination_announcement_datetime < timezone.now()

    def has_voting_started(self):
        if not self.election_vote_start_datetime:
            return
        else:
            return self.election_vote_start_datetime < timezone.now()

    def has_voting_closed(self):
        if not self.election_vote_end_datetime:
            return
        else:
            return timezone.now() > self.election_vote_end_datetime

    def is_voting_open(self):
        # If no election voting start is specified, the voting is
        # always closed.
        return self.has_voting_started() and \
               not self.has_voting_closed()

    def is_city_results_due(self, city_code):
        if city_code == 'R' or city_code == '':
            return self.riyadh_results_datetime and \
            self.riyadh_results_datetime < timezone.now()
        elif city_code == 'J':
            return self.jeddah_results_datetime and \
            self.jeddah_results_datetime < timezone.now()
        elif city_code == 'A':
            return self.alahsa_results_datetime and \
            self.alahsa_results_datetime < timezone.now()

    def __unicode__(self):
        return "%s-%s" % (self.start_date.year, self.end_date.year)


class Position(models.Model):
    title = models.CharField("اسم المنصب",
                             max_length=55)
    entity_choices = (
        ('club', 'نادي الطلاب'),
        ('council', 'المجلس الطلابي الاستشاري'),
        )
    entity = models.CharField("اسم المنصب",
                              default="club",
                              max_length=50,
                              choices=entity_choices)
    city = models.CharField("المدينة", max_length=1, blank=True,
                            default="", choices=city_choices)
    colleges_allowed_to_vote = models.ManyToManyField(College,
                                                      verbose_name="الكليات المسموحة بالتصويت",
                                                      related_name='voting_positions')
    colleges_allowed_to_nominate = models.ManyToManyField(College,
                                                          verbose_name="الكليات المسموحة بالترشيح",
                                                          related_name='nomination_positions')
    note = models.TextField("ملاحظة", blank=True)
    submission_date = models.DateTimeField("تاريخ التقديم", auto_now_add=True)
    modification_date = models.DateTimeField("تاريخ التعديل", auto_now=True, null=True)
    year = models.ForeignKey(SACYear, verbose_name="السنة")

    class Meta:
        verbose_name = 'المنصب'
        verbose_name_plural = 'المناصب'

    def get_total_votes(self):
        return self.votenomination_set.filter(is_counted=True).count()

    def get_uncounted_vote_count(self):
        return self.votenomination_set.filter(is_counted=False).count()

    def get_blank_vote_count(self):
        return self.votenomination_set.filter(nomination_announcement__isnull=True).count()

    def get_blank_vote_percentage(self):
        total_count = self.get_total_votes()
        if not total_count:
            return 0
        blank_count = self.get_blank_vote_count()
        percentage = float(blank_count) / float(total_count) * 100
        return "{:.2f}".format(percentage)

    def get_winner(self):
        if self.nominationannouncement_set.exists():
            return self.nominationannouncement_set.filter(votenomination__is_counted=True)\
                                                  .annotate(vote_count=Count('votenomination'))\
                                                  .order_by('-vote_count')\
                                                  .first()
        elif self.unelected_winner:
            return self.unelected_winner
        else:
            return None

    def is_elected(self):
        if self.nominationannouncement_set.exists():
            return True
        else:
            return False

    def __unicode__(self):
        return self.title

class Nomination(models.Model):
    plan = models.FileField("الخطة")
    cv = models.FileField("السيرة الذاتية")
    certificates = models.FileField(null=True, verbose_name="الشهادات والمساهمات")
    gpa = models.FloatField("المعدل الجامعي", null=True)
    user = models.ForeignKey(User, verbose_name="المرشَّح")
    position = models.ForeignKey(Position, verbose_name="المنصب")
    is_rejected = models.BooleanField(default=False)
    submission_date = models.DateTimeField("تاريخ التقديم", auto_now_add=True)
    modification_date = models.DateTimeField("تاريخ التعديل", auto_now=True, null=True)

    class Meta:
        verbose_name = 'المرشحـ/ـة'
        verbose_name_plural = 'المرشحون/المرشّحات'

    def __unicode__(self):
        try:
            name = self.user.profile.get_ar_full_name()
        except ObjectDoesNotExist:
            # If no profile
            name = self.user.username
        return "ترشّح %s لِ%s" % (name, self.position.title)

class NominationAnnouncement(models.Model):
    plan = models.FileField("الخطة", default="")
    cv = models.FileField("السيرة الذاتية", default="")
    user = models.ForeignKey(User, verbose_name="المرشَّح", default="")
    position = models.ForeignKey(Position, verbose_name="المنصب")

    class Meta:
        verbose_name = 'المرشحـ/ـة المؤهلـ/ـة'
        verbose_name_plural = 'المرشحون/المرشّحات المؤهلون/المؤهلات'

    def get_counted_count(self):
        return self.votenomination_set.filter(is_counted=True).count()

    def get_percentage(self):
        total_count = self.position.get_total_votes()
        if not total_count:
            return 0
        nomination_count = self.get_counted_count()
        percentage = float(nomination_count) / float(total_count) * 100
        return "{:.2f}".format(percentage)

    def __unicode__(self):
        try:
            name = self.user.profile.get_ar_full_name()
        except ObjectDoesNotExist:
            # If no profile
            name = self.user.username
        return "تأهُّل %s لِ%s" % (name, self.position.title)

class VoteNomination(models.Model):
    user = models.ForeignKey(User, verbose_name="المصوِّت")
    position = models.ForeignKey(Position, verbose_name="المنصب", null=True)
    nomination_announcement = models.ForeignKey(NominationAnnouncement, verbose_name="المرشَّح", null=True, blank=True)
    is_counted = models.BooleanField(default=True)
    submission_date = models.DateTimeField("تاريخ التقديم", auto_now_add=True)
    modification_date = models.DateTimeField("تاريخ التعديل", auto_now=True, null=True)

    class Meta:
        verbose_name = 'صوت'
        verbose_name_plural = 'الأصوات'

    def __unicode__(self):
        if not self.nomination_announcement and \
           self.position:
            name = self.position.title
        elif self.nomination_announcement:
            try:
                name = self.nomination_announcement.user.profile.get_ar_full_name()
            except ObjectDoesNotExist:
                # If no profile
                name = self.nomination_announcement.user.username
        else:
            name = ""

voting/forms.py
# -*- coding: utf-8  -*-
from __future__ import unicode_literals
from django import forms
from . import models
from dal import autocomplete

class NominationForm(forms.ModelForm):
    class Meta:
        model = models.Nomination
        fields = ['plan', 'cv', 'certificates', 'gpa']

# To be used in the admin interface, for autocompletion field.
class UnelectedWinnerForm(forms.ModelForm):
    class Meta:
        model = models.UnelectedWinner
        fields = ('__all__')
        widgets = {
            'user': autocomplete.ModelSelect2(url='voting:user-autocomplete', attrs={'data-html': 'true'})
        }

voting/templates/voting/add_nominee.html
{% extends 'base.html' %}{% load bootstrap3 %}

{% block title %}الترشيح لِ{{position.title}}{% endblock %}

{% block header %}
                        <h1>الترشيح لِ{{position.title}}</h1>
                        <small>بوابة ترابط</small>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
                           {% if position.entity == 'club' %}
                            <li><a href="{% url 'voting:list_positions' 'club' %}">مناصب نادي الطلاب</a></li>
                           {% else %}
                            <li><a href="{% url 'voting:list_positions' 'council' %}">مناصب المجلس الاستشاري</a></li>
                           {% endif %}
                            <li class="active">{{ position.title }}</li>
                        </ol>
{% endblock %}

{% block content %}
{% if already_on %}
<p class="alert alert-danger" style="font-size: 18px; color: black;">سبق أن ترشّحت  لمنصب في {{ position.get_entity_display }}! يمكنك الترشّح لمنصب واحد فقط.</p>
{% else %}
<p class="alert alert-warning" style="font-size: 18px; color: black;">
{% if position.entity == 'club' %}
يحتوي ملف الخطّة الرؤى والخطط والبرامج المقترحة، وكذلك فرق العمل للمترشحين والمترشّحات لتمثيل الكليات.
{% elif position.entity == 'council' %}
يحتوي ملفّ الخطّة أبرز المعوقات التي تواجه طلاب أو طالبات كليتك مع الحلول المقترحة لها.
{% endif %}
</p>
<form method="post" enctype="multipart/form-data">
    <div class="col-sm-8">
        {% csrf_token %}
        <div class="row">
            <div class="form-group">
                {% bootstrap_field form.plan %}
                {% if position.entity == 'club' %}
                    <span class="help-block small"><a target="_blank" href="https://goo.gl/IdQjuH">ملف الترشح (يستلزم تعبئة الرؤى والخطط وفرق العمل إن وجد)</a> </span>
                {% elif position.entity == 'council' %}
                    <span class="help-block small"><a target="_blank" href="https://goo.gl/rkN4Ko">ملف الترشح (يستلزم ذكر أبرز العقبات مع حلول لها)  </a> </span>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                {% bootstrap_field form.cv %}
                <span class="help-block small"><a target="_blank" href="https://goo.gl/ceKPnM">نموذج السيرة الذاتية</a> </span>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                {% bootstrap_field form.certificates %}
            </div>
        </div>

        <div class="row">
            <div class="form-group">
                {% bootstrap_field form.gpa %}
            </div>
        </div>

        </div>
<div class="form-group">
<div class="col-sm-8 checkbox checkbox-success">
     <input id="checkbox1" type="checkbox">
     <label for="checkbox1">أقر بالموافقة على <a target="_blank" href="http://sac.ksau-hs.edu.sa/index.php/rules/13-%D9%84%D8%AC%D9%86%D8%A9-%D8%A7%D9%84%D8%A7%D9%86%D8%AA%D8%AE%D8%A7%D8%A8%D8%A7%D8%AA-%D8%A7%D9%84%D8%B7%D9%84%D8%A7%D8%A8%D9%8A%D8%A9">شروط الترشيحات والانتخابات.</a></label>
</div>
</div>
<div class="form-group">
<div class="col-sm-8 checkbox checkbox-success">
     <input id="checkbox2" type="checkbox">
     <label for="checkbox2">أقر بأن جميع المعلومات التي تم تعبئتها في نموذج التسجيل في البوابة وفي هذا النموذج صحيحة، وأنه في حال اكتشاف أي معلومات مغلوطة يحق للجنة الانتخابات استبعادي من الترشيحات الطلابية حتى بعد فوزي بالمنصب.</label>
</div>
</div>
<div class="form-group">
<div class="col-sm-8 checkbox checkbox-success">
     <input id="checkbox3" type="checkbox">
     <label for="checkbox3">أوافق على نشر السيرة الذاتية وملف الترشح.</label>
</div>
</div>
<div class="form-group">
<div class="row">
    <div class="col-sm-12">
    <input id="submit" disabled class="btn btn-btn-success" type="submit" value="أرسل">
    </div>
</div>
</div>
</form>
{% endif %}
{% endblock %}
{% block customscript %}
<script>
$(function(){
   $("input[type=checkbox]").change(function(){
      if ($("input[type=checkbox]:checked").length == 3){
       $("#submit").removeAttr('disabled');
      } else {
       $("#submit").attr('disabled', 'disabled');
      }
   })
});
</script>
{% endblock %}

voting/templates/voting/announce_club_nominees.html
{% extends 'base.html' %}
{% block title %}إعلان ترشيحات نادي الطلاب{% endblock %}
{% block header %}
<h1>قائمة المرشحين والمرشحات لنادي الطلاب للعام {{sac_year.get_next_year_name}}</h1>
{% endblock %}

{% block content %}

{% if not sacyear.is_announcement_due %}
    <p class="alert alert-warning" style="color: black; font-size: 18px;">ما زالت الترشيحات جارية.</p>
{% else %}

    {% for position in positions %}
        <p style="font-size: 20px;">* المنصب: {{position.title}}</p>
        <br>
        <div class="row">
            {% for nomination in position.nomination_set.all %}
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                    <div class="panel panel-bd">
                        <div class="panel-body">
                            <div class="statistic-box">
                                <h2>{{ nomination.user.profile.get_ar_full_name }}</h2>
                                <br>
                                <p align="center">
                                    <a href="{{ nomination.plan.url }}">الخطة</a>
                                    ،
                                    <a href="{{ nomination.cv.url }}">السيرة</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}

{% endif %}
{% endblock %}

voting/templates/voting/announce_nominees.html
{% extends 'base.html' %}
{% block title %}إعلان ترشيحات نادي الطلاب{% endblock %}
{% block header %}

{% if entity == 'club' %}
    <h1>قائمة المرشحين والمرشحات لنادي الطلاب للعام {{sac_year.get_next_year_name}}</h1>
{% else %}
    <h1>قائمة المرشحين والمرشحات للمجلس الاستشاري للعام {{sac_year.get_next_year_name}}</h1>
{% endif %}
{% endblock %}

{% block content %}

{% if not sac_year.is_announcement_due %}
    <p class="alert alert-warning" style="color: black; font-size: 18px;">ما زالت الترشيحات جارية.</p>
{% else %}

    {% for position_city, positions in per_city %}
        <h2>مناصب {{ position_city }}</h2>
       {% for position in positions %}
        <p style="font-size: 20px;">المنصب: {{position.title}}</p>
        <br>
        <div class="row">
            {% for nomination in position.nominationannouncement_set.all %}
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                    <div class="panel panel-bd">
                        <div class="panel-body">
                            <div class="statistic-box">
                                <h2>{{ nomination.user.profile.get_ar_full_name }}</h2>
                                <br>
                                <p align="center">
                                    <a href="{{ nomination.cv.url }}" target="_blank" >السيرة</a>
                                    ،
                                    <a href="{{ nomination.plan.url }}" target="_blank">الخطة</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
       {% endfor %}
    {% endfor %}
{% endif %}
{% endblock %}

voting/templates/voting/closed.html
{% extends 'base.html' %}
{% block title %}انتهاء فترة الترشّح{% endblock %}
{% block header %}
                        <h1>انتهاء فترة الترشّح</h1>
                        <small>بوابة ترابط</small>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
                            <li class="active">انتهاء فترة الترشّح</li>
                        </ol>
{% endblock %}
{% block content %}



<p class="text-center" style="font-size: 25px;"><i class="fa fa-exclamation-triangle fa-4x"></i><br>انتهت فترة الترشّح لعام {{ sac_year.get_next_year_name }} يوم {{ sac_year.election_nomination_end_datetime|date:"l j F Y" }}!</p>

{% endblock %}

voting/templates/voting/indicators.html
{% extends 'base.html' %}{% load staticfiles %}
{% block title %}مؤشرات التصويت{% endblock %}
{% block header %}
<h1>مؤشرات التصويت</h1>
هنا نستعرض نتائج الانتخابات!
{% endblock %}
{% block content %}
<style>
.table-striped tbody tr.blank{
 background-color: #cfcfcf
}
</style>

{% for position in election_positions %}
{% cycle "<div class='row'>" '' '' %} 
<div class="col-sm-4">
<h2>{{ position.get_entity_display }}: <a href="{% url 'voting:list_votes_per_position' position.pk %}">{{ position.title }}</a></h2>
<table class="datatable table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>المُرشّحـ/ـة</th>
      <th>عدد الأصوات</th>
      <th>النسبة</th>
    </tr>
  <tbody>
{% for nominaton in position.nominationannouncement_set.all %}
    <tr>
       <td>{{ nominaton.user.profile.get_ar_full_name }}</td>
       <td>{{ nominaton.get_counted_count }}</td>
       <td>{{ nominaton.get_percentage }}%</td>
    <tr>
{% endfor %}
    <tr class="blank">
       <td>امتناع عن التصويت</td>
       <td>{{ position.get_blank_vote_count }}</td>
       <td>{{ position.get_blank_vote_percentage }}%</td>
    <tr>
    <tr class="blank">
       <td>أصوات مُبطلة</td>
       <td>{{ position.get_uncounted_vote_count }}</td>
       <td> - </td>
    <tr>
  </tbody>
</table>
</div>
{% cycle '' '' '</div>' %}
{% endfor %}

{% endblock %}
{% block customscript %}
<link rel="stylesheet" href="{% static 'bdtask/assets/plugins/datatables/dataTables.min.css' %}">
<script src="{% static 'bdtask/assets/plugins/datatables/dataTables.min.js' %}"></script>
<script>
        language = {% include 'js/dataTables-arabic.json' %};
$(function(){
   $(".datatable").DataTable({
                    dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
                    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                    buttons: [
                        {extend: 'copy', className: 'btn-sm'},
                        {extend: 'excel', title: 'ExampleFile', className: 'btn-sm'},
                        {extend: 'pdf', title: 'ExampleFile', className: 'btn-sm'},
                        {extend: 'print', className: 'btn-sm'}
                    ], 
                    order: [[5, 'desc']],
                    language: language});
});

</script>


{% endblock %}

voting/templates/voting/list_club_positions.html
{% extends 'base.html' %}{% load staticfiles %}

{% block title %}مناصب نادي الطلاب{% endblock %}
{% block header %}
                        <h1>مناصب نادي الطلاب</h1>
                        <small>بوابة ترابط</small>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
                            <li class="active">مناصب نادي الطلاب</li>
                        </ol>
{% endblock %}
{% block content %}
<style>
.panel{
   height: 100px;
}

img{
      margin-right: auto;
      margin-left: auto;
      max-height: 200px;
      margin-bottom: 20px;
}

h2{
   font-size: 20px;
   text-align: center;
}

p{
    text-align: center;
}
</style>
<div class="row">
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
<img class="img-responsive" src="{% static 'images/logos/student-club.png' %}">
<p style="font-size: 20px; text-align: justify;">
    يهدف نادي الطلاب إلى الربط بين طلاب الجامعة وطالباتها واكتشاف مهاراتهم وصقلها وتطويرها في مجالات عدة من خلال أنشطة طلابية فارقة، وذلك بإشراف عمادة شؤون الطلاب ودعمها، لتعزيز انتماء الطلبة وولائهم للجامعة. يتمثل دور ممثلي نادي الطلاب في اقتراح وتخطيط وإعداد الأنشطة اللاصفية وتنظيمها للطالب والطالبات.
    <br>
    <strong>كونوا جزءًا من الإنجاز، وقيادات النشاط الطلابي في الجامعة!</strong>
</p>
</div>
</div>
{% if user_nominations.exists %}

<p class="alert alert-warning" style="color: black; font-size: 18px;">تمّ الترشّح للمناصب التالية:</p>
{% for nomination in user_nominations %}
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                            <div class="panel panel-bd">
                                <div class="panel-body">
                                    <div class="statistic-box">
                                        <h2><a href="{% url 'voting:show_nomination' nomination.position.pk nomination.pk %}">{{ nomination.position.title }}</a></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
{% endfor %}
{% else %}
{% for position in positions %}
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                            <div class="panel panel-bd">
                                <div class="panel-body">
                                    <div class="statistic-box">
                                        <h2><a href="{% url 'voting:add_nominee' position.pk %}">{{ position.title }}</a></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
{% endfor %}
{% endif %}
{% endblock %}

voting/templates/voting/list_positions.html
{% extends 'base.html' %}

{% block title %}قائمة المناصب{% endblock %}
{% block header %}
                        <h1>مناصب المجلس الاستشاري</h1>
                        <small>بوابة ترابط</small>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
                            <li class="active">مناصب المجلس الاستشاري</li>
                        </ol>
{% endblock %}
{% block content %}

<h2>قائمة المناصب</h2>

{% for position in positions %}

    <a href="{% url 'add_nominee' position.pk %}">{{ position.title }}</a>
    <br>

{% endfor %}


{% endblock %}

voting/templates/voting/nomination_thanks.html
{% extends 'base.html' %}{% load staticfiles %}
{% block title %}استلمنا ترشّحك!{% endblock %}
{% block header %}
                        <h1>استلمنا ترشّحك!</h1>
                        <small>بوابة ترابط</small>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
                        </ol>
{% endblock %}
{% block content %}
<div class="text-center">
<p style="font-size: 25px;">ستعلن أسماء المترشحين والمترشّحات يوم {{ sac_year.election_nomination_announcement_datetime|date }}!</p>
</div>
{% endblock %}

voting/templates/voting/show_nomination.html
{% extends 'base.html' %}
{% block title %}ترشّح {{ nomination.user.get_ar_full_name }} ك{{ nomination.position.title }}{% endblock %}
{% block header %}
                        <h1>ترشّح {{ nomination.user.get_ar_full_name }} ك{{ nomination.position.title }}</h1>
                        <small>بوابة ترابط</small>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'home' %}"><i class="pe-7s-home"></i> الرئيسية</a></li>
                           {% if nomination.position.entity == 'club' %}
                            <li><a href="{% url 'voting:list_positions' 'club' %}">مناصب نادي الطلاب</a></li>
                           {% else %}
                            <li><a href="{% url 'voting:list_positions' 'council' %}">مناصب المجلس الاستشاري</a></li>
                           {% endif %}
                            <li class="active">{{ nomination.user.profile.get_ar_full_name }}</li>
                        </ol>
{% endblock %}
{% block content %}
<table class="table table-hover">
   <tr>
      <th>الخطّة</th>
      <td><a href="{{ nomination.plan.url }}">{{ nomination.plan.name }}</td>
   </tr>
   <tr>
      <th>السيرة</th>
      <td><a href="{{ nomination.cv.url }}">{{ nomination.cv.name }}</td>
   </tr>
   {% if nomination.certificates %}
   <tr>
      <th>الشهادات والمساهمات</th>
      <td><a href="{{ nomination.certificates.url }}">{{ nomination.certificates.name }}</td>
   </tr>
   {% endif %}
</table>
{% endblock %}

voting/templates/voting/voting.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block title %}التصويت{% endblock %}

{% block body %}



{% endblock %}